version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: express_app
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3002:3000"
    environment:
      MONGO_URI: "mongodb://localhost:27017/SIT725GroupProject"

volumes:
  mongodb_data: